export const arbDaoTxT: string=
`
Arbitrum

5
Apr2023
AIP-1.1-Lockup,Budget,Transparency
UPDATE:
Itisnowliveforanon-chainvoteTally|ArbitrumProposalEditedupdate:Thepreviousproposalwasmisconfigured,thecorrectlysetuponecanbeviewedatTally|ArbitrumProposal
UPDATE:
BlockworksResearchhasputAIP-1.1liveonSnapshot:
https://snapshot.org/#/arbitrumfoundation.eth/proposal/0x7203289844e807781e8d2ec110d4b97a79a29944cae06a52dbe315a16381a2ae

Abstract
tl;dr:Thisproposalproposes(1)alockup,(2)abudgetand(3)transparencyreportingregardingthe7.5%ofthe$ARBtokensdistributedtotheFoundation’s“AdministrativeBudgetWallet”.

TheAdministrativeBudgetWalletwillbeusedforcoveringongoingadministrativeandoperationalcostsofTheArbitrumFoundation,paymentofserviceproviders,andforthepurposeoffosteringthegrowthanddevelopmentoftheArbitrumecosystem.Inrespecttothe7.5%thathasbeendistributedtotheAdministrativeBudgetWallet,atransparencyreportregardingthe0.5%thathasalreadybeentransferredisavailablehere291.

Theremaining7%oftokenswillnotbeuseduntiltheapprovalofabudget,suchastheoneproposedinthisAIP.Theproposedbudgetisin-linewiththeFoundation’sstrategicneedstorepresentandservicetheDAOandtheallocationissmallerthaninitialallocationstopeerfoundations.ThisAIPproposesplacingthe7%outstandingdistributioninasmartcontract-controlledlockup–linearlyunlockingover4years–alongsidetransparencyreportstructurestoallowtheDAOtoperiodicallymonitorexpendituresandotheractivitiesoftheFoundation.

TheAdministrativeBudgetWalletwillbeusedinpursuitoftheFoundation’smissionstatementassetoutinthebylaws55,whichincludesfinancingtechnicalimprovementsandoperationsoftheArbitrumnetwork,fosteringecosystemgrowththroughgrantstoalignwithpartnerprojectsandeducationalinitiativeswithin-personandonlineevents.

Motivation
OnMarch16,2023,theArbitrumnetworks(ArbitrumOneandArbitrumNova)weredecentralizedandgiventothenewlyformedArbitrumDAO.Includedinthistransitionwere:

Controloftheupgradeabilityandtechnicalfutureofthechains
ControlovertheDAOtreasury
Controlovernetfeerevenue-i.e.thenetdifferencebetweenfeescollectedbyon-chainoperationsandL1feespaidbytheSequencer
AllArbitrumsocialmediaplatformsandaccounts
Abilitytoelectand,ifdeemedappropriate,removetheSecurityCouncilandDirectors
Fullresponsibilityofthechain’stechnology,future,andfeerevenueweregiventotheDAOdirectly.WiththeDAOassumingthoserightsandcontrols,theDAOalsoassumedtheresponsibilitytofundtheongoingoperationsofthechainsandthecostsofrunningcriticalchaininfrastructure,includingRPCs,theSequencer,andthird-partyvendorsandservicecontracts.

WhiletherearemanyactivitiesthattheDAOcandodirectlyon-chain,severalofitsresponsibilitiesrequirearepresentativethatcanengage,maintainandenternewagreementswithserviceproviderstoruninfrastructurethat’scriticalfortheecosystem(e.g.servers,RPCs,blockexplorers,datafeedsandanalyticsplatforms,andtooling),andensurethatboththechainandtheecosystemhavethesupporttheyneedtocontinuetothrive.InordertoensureasmoothtransitiontotheDAOwithoutanyinterruptionofservices,itwasnecessarytocreateanorganizationthatwouldbereadytoservicetheDAOimmediatelyfromlaunch.

TheArbitrumFoundationwascreatedtofillthisneed,withitsmissionandscopeoutlinedacrosstheFoundationBylaws55.PriortothelaunchingoftheDAO,TheArbitrumFoundationassumedresponsibilitiesforfundingandrunningchaininfrastructure.However,inanarrangementthatappearstobeuniqueamongstArbitrum’speers,theFoundationdoesnotreceiveorcontrolthenetrevenuefromtransactionfeesasthisisgivendirectlytotheDAOtreasury.

TheDAOisalsotaskedwithfosteringanddevelopingtheArbitrumecosystem,wheretheDAOmayseektopartnerwithcompaniesororganizationsthateithercannotorwillnotpubliclynegotiatecollaborationsorpartnershipsduetoconfidentialityandotheroperationalrequirements.Often,largeenterprisesnegotiatepartnershipopportunitiesinprivatewithoutpublicprocesses,wheretheserelationshipscanonlybedisclosedaftertheyareagreedupon.Havingawell-fundedFoundationempoweredtorepresenttheDAOinthisarena,alongsidepeerfoundations,isinthebestinterestsoftheDAOtofurtherdevelopthegrowthoftheArbitrumecosystem.

Rationale
WhiletheneedfortheFoundationtoexistandrepresenttheDAOiswell-motivated,itbecameclearthroughcommunitydiscoursearoundAIP-1thatitwasimportanttohaveadditionalinsightandrestrictionsontheFoundation’sinitialfunding.ThisAIP-1.1proposesadetailedsetofcontrolsandinitiativestoachievethatgoal.

1.SmartContractLockup

Theremaining7%ofARBtokensinthe“AdministrativeBudgetWallet”willbesubjecttoafouryearlockupschedule,unlockingonacontinuouslineartimebasiscommencingfromthedateoftheSnapshotapprovalofAIP-1.1bytheDAO(i.e.,atotalof175m$ARBreleasedovereachyearfor4years).Thelockupwillbeenforcedon-chainthroughasmartcontractwhichwilldesignateamultisigwalletcontrolledbyTheArbitrumFoundationasthebeneficiary.ThelockupcontractwillbeconfiguredinamannerthatallowstheDAOtoadjustfuturefundingand/ormodifytheunlockschedule.

2.OperatingBudget

BelowisaproposedannualoperationalbudgetforthefirstyearoftheFoundation.WhiletheoperationalcostsaredenominatedinUSD,theexpectationisthatapproximatelyhalfwillbepaidinUSDandhalfwillbepaidinlocked$ARBtokens.

AsthiswillbethefirstyearoftheFoundation’soperationandastheFoundationisstillyoungatthetimeofthisAIP,itgoeswithoutsayingthattheseareestimateswiththeexpectationthatthiswillbeanupperboundontheoperationalcostsforthefirst12months.Thetransparencyreportsdescribedinthenextsectionwillbeanopportunitytotracktheactualexpensesagainstthebudgetedcategoriesandkeepthecommunityinformed.

OperatingBudget	
Cost($USD)
GeneralandAdministrative	$16,000,000
R&D	$9,000,000
TechnicalInfrastructure	$5,000,000
Events,Marketing&Communications	$6,000,000
Total-NextTwelveMonths	$36,000,000
(50%$USD/50%$ARB)
*TheGeneralandAdministrativeline-itemincludespersonnel,contractors,legal,insuranceandotheroperationalcosts.AsofthedateofthisAIP,theFoundationcurrentlyhasfivefull-timecontributors,8contractors,andtheSecurityCouncilengagedtosupporttheArbitrumecosystem.TheFoundation’sbudgetanticipatestheneedtohireanadditional15full-timecontributorsacrosstechnical,growthandcommunityfunctionsoverthecourseofthisyear.

Thisoperatingbudgetpresentsbest-faithestimatesoftheFoundation’santicipatedbudgetaryneedswhichmaybesubjecttochange.

3.EcosystemGrowthInitiatives

Anyadditionalfundsreleasedincompliancewiththelock-upscheduleabovewillbemadeavailable,butnotnecessarilydeployed,toopportunisticallypursueecosystemgrowthopportunitiesandstrategicpartnershipsonbehalfoftheDAO.Theexpectationisthatthevastmajorityofecosystemgrowthfundswillbepaidintokens,andthuswillnotrequiretheFoundationtosellanytokens.Whereverreasonable,theFoundationwillincludeadditionallockupsand/orvestingwhenmakingdistributionsintokens.

TheMissionStatementintheFoundation’sbylaws55highlightsthevariednatureoftheopportunitiestheFoundationintendstopursue,andasetofKPIsthatcantrackalloftheseopportunitiesbeingdeveloped.ThebasisofthoseKPIswillstemfromafocusononboardingandgrowingboththedeveloperanduserbaseoftheArbitrumecosystem,attractingbest-in-classinfrastructureproviderstothenetwork,expandingacrossvariousindustries,use-casesandscopeofprojectsthatengagewithArbitrumtechnology.TheultimategoaloftheFoundationistocontinuetofosterthedevelopmentofthetechnologyandexpandtheArbitrumecosystemglobally.

InadditiontotheFoundation’sprocessesforselectinggrants,itisimportanttonotethattheDAOmaintainscontroloverthe3.527billion$ARBandhastheabilitytodistributeanyadditionalgrantsasitseesfit.Additionally,shouldtheDAOchoose,ithastheabilitytotriggertheinflationofthetotalsupplyof$ARBwhichwillsupplementtheon-chainDAOtreasurywith2%growthofthetotalsupplyof$ARBeachyear.

4.TransparencyReports

TheFoundationunderstandsandagreesthatthecommunityshouldhaveoversightacrosshowthesefundsarebeingutilizedtogaincomfortthatspendingisintheinterestofthecommunity.Infurtheranceofthisgoal,theFoundationiscommittedtoprovidingacomprehensiveannualreportandasemi-annualprogressupdate.ThiswillprovidethecommunitywithabetterunderstandingoftheFoundation’sexpenditures,balancesheetanditspursuitofecosystemgrowthopportunitiesalongsidepartnershipdevelopments,aswellasthevariousinternalandexternalcommitteesandstakeholdersthatareinvolvedinthedecisionmakingprocess.

TheFoundationiscontinuingtobuildoutitsinternalpersonneltoservicegrantrequestsandhasalreadyengagedaDAOserviceprovidertoassistwiththeadministrativecomponentsofservicinggrants.TheFoundationisalsotalkingwithanumberofdifferentexternalserviceproviderstoassistinboththereviewanddiligenceprocesses.

ThefinancialelementofthesetransparencyreportswillincludeabreakdownofoperationalcostsincurredwhilerunningtheFoundation,includinginfrastructurespendingfortheArbitrumchains,events,communitybuildingefforts,grants,etc.

Inadditiontotheaforementionedreports,theFoundationisprovidinganinitialtransparencyreportalongsidethisAIPcoveringallmajoractionsanddecisionstheFoundationmadeduringset-up,includingthecostsincurredupuntilnow,whichcanbefoundhere291.

StepstoImplement

Foundationtodeploysmartcontractvestingwalletinthespecifiedconfigurationandtransfer700million$ARBtoit.
FoundationtoimplementallprocessesdescribedinthisAIP.
Timeline

ThisAIP-1.1shallbepostedontheDAOforumandwillhaveatleasta72-hourperiodforDAOcommentsandinput.Aftertheendofthe72-hourperiodandappropriateupdatesincorporatingDAOfeedback,thisAIP-1.1willbepostedforvoteonSnapshotforanadditional7days.

7Replies
81

​
created
Apr2023
lastreply
Jul2023
89
replies
21.5k
views
76
users
479
likes
32
links
FrequentPosters
5
3
3
2
2
2
2
2
















PopularLinks
293	Transparencyreport:Initialfoundationsetup|ArbitrumDAO-Governancedocsarbitrum.foundation
72	Proposal:Return700M$ARBtotheDAOTreasuryarbitrum.foundation
55	CurrentBylaws.pdf-GoogleDrivegoogle.com
38	Snapshotsnapshot.org
34	Tally|ArbitrumProposaltally.xyz
​
Thereare89replieswithanestimatedreadtimeof28minutes.


Showtopreplies

PinnedonApr6,2023


Lenny
Apr2023
Soacontractorreceivesroughly400kyearlycomp?Soundslikealot

2Replies
9


DisruptionJoe
Apr2023
Inrespecttothe7.5%thathasbeendistributedtotheAdministrativeBudgetWallet,atransparencyreportregardingthe0.5%thathasalreadybeentransferredisavailablehere.

Notonlyis7.5%muchlessthanpeers(Optimism25%),butthistransparencyreportisbeyondwhatIhaveseenatanyDAOusingthistypeofstructure.

Overall,thisplustheothertwodocumentsareagreatstepforward.Iplantovoteinfavoroftheupdatesandamendments.

Thankyouforaddressingthecommunityconcerns.

2Replies
34


Epic
Apr2023
thisisgoodwork!Iamwaitingforsnapshot

7


niklas67
Apr2023
Youliedandstole750milliontokensanddidspend50million,noyouwanttokeeptherestyoudidstealjustgetitfromasmartcontract.Payitbacktothefoundationandwaitforthevotes,youarestilltryingtokeepthestolencoins.Thetrustforthisprojectishurttothecore,whyshouldwetrustyourliesthistime.

2Replies
8


eli_defi
Leader

DisruptionJoe
Apr2023
Appreciatetheperspective!Alotofworkwentintoaddressingallofthecommunityfeedback!:blue_heart::orange_heart:

11


ibuyshite

Lenny
Apr2023
from16M720kwillbforsecuritycouncilmember(consistsof12members,eachgettingpaid5kpermonth)

remains15.28millionwhichwillbedistributedtoremaining5contributorsand8contractors…alsotheyarelookingtohiretotal15contributorinayear…soevenifwelookatthosenumbers…andtake30membersforex:
itwill500k+perpersonand400k

2Replies
7


DreepyGecko
Apr2023
Mateyoucan’tjustdividetheentireGeneralandAdminbudgetbyheadcount,itincludeswaymorethanjustsalaries-theyevensayitincludesinsurance,legalandotheroperatingcostsrightinthepost.

Byyourlogic,everyemployeeatWendysmustbemakinglike$200k

12


haku
Apr2023
Fairpoint.Itwouldbenicetohavesomegranularityonceaquarterregardingthesebroadbucketsthey’veused.Whentheexpensesstartrollingin,itwouldbegreattodrilldownfurthertoensurethatthereisnofraudulentorrecklessspending.

11


PhiMarHal

DisruptionJoe
Apr2023
Happywiththerework.QuotingJoe’spostforemphasis,asitreflectsmythoughts.Goodjob!

11


hiringdevs.eth
Apr2023
Iamlargelyinfavorofthisproposal,buthaveafewpointsIwouldlikeclarificationaround.

Moredetailedbudget
Theincludedoperatingbudgetisverylargewithoutmuchclarificationaroundwherethefundsaregoing.Canwegetmoreclarityaroundbudgetsforpayroll,operatingexpenses,grants,etc.?Understandingtheuseoftheproceedswillalsohelpusunderstandtheexpectedimpactweshouldseefromtheexpense.
Communitygovernedroles
Currentlyallofthebudgetisplannedtogotowardsacentralizedteamof20FTEs.Especiallyasweconsidertheimpactofthisprogramoverthenext4years,itwouldbegoodforthecommunitytobeabletovoteinnewrepresentativesforachangeinstrategy.ThiscouldbedoneinamannersimilartomanyofthetopDAOgrantsprogramswhereelecteddelegatesareresponsibleforsourcing,vetting,andallocatinggrants.Additionally,serviceorgslikeGauntletorReveriecouldbecontractedforspecificoperations.
ClarityaroundsaleofARBtoUSD
Thereisamentionof50%inUSDand50%inARB.Canwegetclarityaroundtheexpectedsaletimelineforthesefunds?
13


elwowso
Apr2023
Appreciatetherework.Thankyoufortheclarity.

3


Alexnguyen1881.Arb
Apr2023
Iagreetotheseamendmentsandsuggestions.Ifyouthinkthatoperatingexpensesonlypaysalariesforemployees,youarewrong.Therearemanyhiddencostsanditaccountsfor80%ofthetotalcost.Expandyourhorizonsandgivetheteamachancetobuild.Youwantyourinvestmenttoincrease10to20timesanddon’twantthecoreteamtohaveenoughoperatingcosts?haha

5


mrbnaik
Apr2023
Appreciatetherework.Thankyoufortheclarity.

3


vikas21st
Apr2023
letseewhateffectsseenonprices

3


thiccythot

11
Apr2023
Iamconfusedaboutthedecisiontoallocate750MtokensfromtheDAOtotheFoundationwithoutanygovernancedecisionmadefromtheDAO.

Medium–16Mar238



ARBITRUM:THENEXTPHASEOFDECENTRALIZATION8
TherewasnomentionofanyFoundationallocationinthe“prospectus”thatwasdistributedbeforeallowingthegovernancetokenstobetradedonexchangeandIthinkthisshouldbeviewedaslegallybinding.

Renegingonthecommunicationssetoutintheprospectusafterinvestorsmadefinancialdecisionstopurchasethegovernancetokenontheopenmarket(byaliquidityproviderthattheserviceprovidercontractedtheservicesof)isundeniablyfraudulent.

image
image
1000×87238.5KB
GoingforwardwithratifyingAIP-1isaclearoverreachbytheserviceprovideroftheDAO’spower.ThisisanunacceptableprecedenttosetasitclearlysubordinatestheDAOtoanyfuturedecisionsbytheserviceprovider.

Theallocationofthe750MtokenssenttothefoundationshouldbesentbacktotheDAOimmediately,theagreementwithWintermuteshouldbenullified,andanytokenssoldontheopenmarketonbehalfofthefoundationshouldbeboughtbackontheopenmarket.

TheserviceprovidersaresubordinatetothedecisionsoftheDAOituntilitstokenvestinayearandcanmakegoverningdecisions.

ThereneedstobeaclearprecedentthatthegovernancetokenholdershavefullauthorityandcontrolovertheDAO’streasuryresourcesandanyallocationsofsaidresources.

Iampersonallyopentoallocating7.5%orevenmoretothefoundation,butitmustcomefromthedecisionofthegovernanceholders,nottheserviceprovider.

1Reply
10


litocoen
Apr2023
welcomethesestepstocreatemoretransparencyandaccountabilityovertheFoundation’soperations!

3


0xYield

thiccythot
Apr2023
Howisthatevenlegal!
Thespaceneedstobemoretransparentwithmarketactivities,nowondertheSECiscrackingdownonussomuchrecently!
ImvotingNO!

3


Lenny

ibuyshite
Apr2023
Yes,Iwasleavingamarginthereforwhatever.So,youthinkthisisalright?




LFG
Apr2023
Convertyour10MUSDfiatbackto$ARBandsendbackyourstolen50M$ARB,lockwhatyoushouldlockforcorrectyearsaspromised.Neverlietocommunity.
AsNO.1inL2,youhavemanywaystoearnmoreandmoremoneyinthecomingfuture,don’tbesooooooooooshortsighted.

2


Westbrook

niklas67
Apr2023
Aye,Theappropriatedisposalmethodistoreturn50millioncoinsasAIP-1didn’tapproved

1


ViktorGPT
Apr2023
badideabecauseallmoneynotforDAO

1


Adtianzzz

3
Apr2023
ThemostimportantthingisthatyoushouldbringbasicconfidenceofARBDAObyillustratingdetailsofthespendingofthat10mARB.Howcanwetrustateamcasuallyspendinvestormoneyforbeersandgirls!

Secondly,furtherrequirementsoftokenshouldbewithdetailsofforwardusage.Everycompanyshouldhaveandaccountandbudget!

BUTafterall,Forthisapithetokendistributionisokforme,hopeyouguysreallydosomething!

1


Big_Noodle
Apr2023
IwanttothanktheArbitrumteamforconsideringcommunityfeedbackandupdatingtheAIPtomakeitmoretransparent.It’sapositivestepforwardfortheFoundation.

I’veseenalotofcommentsabouttheloanforMM,andwhilemoreclarificationwouldbehelpful,let’stakethingsonestepatatime.

IplantovoteinfavorofAIP-1.1.

5


Zeb
Apr2023
Isitjustmeoristhetransparencyreportnotsayingmuch?BasicallyinfoofAIP1,butinadocsformat?

AlsostillthinkitisabsurdthattheArbteamisrequestingsuchahugeamountin1go.Startsmall.Proveyourworth.Askforanewbudgeteachquarter.

AndridiculousthatOffchainLabsmembersaregettingpaid5ktobeonamultisig.WhythegreedforthisextraARB?Comparedtoyourcompanyfunding,salaryandARBteamallocation,whydoyoufeeltheneedtoaskfor5k?Fortheotherpeopleonthemultisig,thereisacasetobemade.ButforOffchainLabsmembers…seriously?

5


limes
Apr2023
Thankyouforproposing,AIP-1.1-Lockup,Budget,Transparency,whichgivesusabetterideaofhowtheArbitrumFoundationallocationwillbeissuedandused.However,Istillhavesomequestions.

Controlovernetfeerevenue-i.e.thenetdifferencebetweenfeescollectedbyon-chainoperationsandL1feespaidbytheSequencer

(1)Whatdoescontrolmeanhere?IsthereawalletthatcollectstheETHmadeinfees?HowdoestheDAOcollectthisrevenue?IsitcurrentlygoingtoOffchainLabs?

OperatingBudget	
Cost($USD)
GeneralandAdministrative	$16,000,000
R&D	$9,000,000
TechnicalInfrastructure	$5,000,000
Events,Marketing&Communications	$6,000,000
Total-NextTwelveMonths	$36,000,000
(50%$USD/50%$ARB)
(2)Ifthisisthefoundation’syearlyburnrate,andyou’dliketosecurea4-yearrunratefromtheDAO,assuming$ARBholdsitspricearound$1.20,adjustingforthe50millionalreadyspent,whatistheneedfortheadditional$796millionin$ARB?(50x1.2=60,36x4=144,1000-144-60=796).

Anyadditionalfundsreleasedincompliancewiththelock-upscheduleabovewillbemadeavailable,butnotnecessarilydeployed,toopportunisticallypursueecosystemgrowthopportunitiesandstrategicpartnershipsonbehalfoftheDAO

HavingexperienceinthisrealmwithENSDAO,Irecognizetheimportanceofthis,butinnowayseehow$796millionover4yearscouldbeeffectivelyallocated.

(50%$USD/50%$ARB)

(3)Whatdoesthismean?Theaskisfor750million$ARB.AreyousayingyouintendtoholdhalfandconverthalftoUSD?$ARBmightaswellstayintheDAOtreasuryifyoudon’tintendtospend.

(4)Whathappensintheeventofabudgetoverrun?AsktheDAOformoremoneyagain?4yearsistoolongofatimehorizontofundfortheDAOtoassesswhetherornotthefoundationsinterestsalignwiththecommunityandecosystem.

TheArbitrumFoundationisthebestteamtohandle,maintain,andenternewagreementswithserviceproviderstoruninfrastructurethat’scriticalfortheecosystem.Theexperienceandknowledgeontheteamisextremelyvaluable.ButthisisthelevelofscrutinyneededtooperateaDAO.I’llvoteagainstAIP1.1initscurrentform.

Thecriteriaformetochangemyvotewouldbetolowerthedollaramounttothatwhichthefoundationhasaplan($36million/year)tospendandmaketheproposalannualasopposedtooncefor4years.Iwouldbeinfavorofkeepingthetimelocktoalignincentivesasabonuspoolforemployeesandcontractors,but,wouldliketolowerthisamounttoamorereasonablelevel.

1Reply
13


ChronoFury
Apr2023
Thoughtheoperatingbudgetisonthehigherend,itisnotcompletelyunreasonable.Hopethatthefoundationwouldmakefulluseofthesefundstogrowtheecosystemasmuchaspossible.

Willbevotingyes.

3


ibeace
Apr2023
Soundslikealottome.




F666
Apr2023
Ithinkthemostsincerewayforthefoundationistoreturnthetokenstothetreasury,andthenre-initiatethefunduseapplicationproposalforthepurposeofusingthefunds.Itwillbemoresincere.Insteadofputtingtokensintoasmartcontractforunlockingtime.Becausethisisjustspendingsometimeandcostontheprevious750milliontokens,whichareunlockedeveryyear,andthencontinuetobetransferredbacktothefoundationinbatches.Thelatterschemehasnoessentialdifferencefromtheaip1scheme.




Jason3s
Apr2023
Hi,thanksfortheamendmentstoAPI1andthenewAIP1.1and1.2.

IhavesomeconcernsonAIP1.1initscurrentformandsomeoftheresponsesonquestionsraisedonAIP1.

Firstlythetransparencyreportnotesthat0.1%ofthe7.5%oftokensallocatedtothefoundationwasusedinsettingupthefoundation,thatequatestoroughly$10-15Matthecurrentprice.Thereportfurtheronlyliststhevariouscoststhesefundswereusedforwithnomonetaryamountsbeingdisclosedortherelevantserviceprovidersandwhattheygotpaid.

Howcoulditcost$10Mtosetuponefoundationcompany?AsimpleGooglesearchrevealsthatincorporatingasinglecompanyintheCaymanIslandscostsabout$2,000-$5,000fortheincorporationandmorecomplexstructuressuchastrustsseemtorunfrom$10kto$50kdependingoncomplexity.

Inherentlythefoundationisnotacomplexentityasoutlinedbytheproposedbudgetwith4lineitems.Thereisnotradingorhighvolumeoftransactions,thefoundationwillmostlypaygrantsandexpensessomaybeacouplehundredtransactionsayear.

Howisitthatthecosttosetupthefoundationissohighwhencomparedtothegeneralsetupandincorporationcostsinthejurisdictionwhichisalreadyhighwhencomparedtootherjurisdictions.

Ithinkitsimportanttodisclosetheprocessinselectingandvettingtheserviceproviders,andlistingtheamountsandcostsindetailtosetupthefoundationtosetaprecedentoftransparencyandtrustandtomakesurethatthefoundation,theDAOandthecommunityarenotbeingtakenadvantageofandhasclearinsightintothisprocess.

Thisconcernisfurtherjustifiedwhenlookingattheproposedbudgetforthenext12months.

image

ThebiggestlineitemisGeneralandAdminwithnobreakdownofwhatthesecostswillentailandwhotheserviceprovidersare.ThisexpenselineisalsoalmostdoubleanyoftheotherproposeditemssuchasR&Dandtechnicalinfrastructurewhichseemmuchmoreimportanttothesuccessoftheecosystem,whichagainbringsmetomyquestionhowcoulditcostthisamountofmoneytorunafoundationcompany?Whatexactlyarethecostsandifitcosts$16MayeartorunacompanyinthisjurisdictionisitthebestchoicefortheArbitrumFoundationtobeincorporatedhere?

ForcomparativesinthehedgefundindustrywhichiswhattheCaymanIslandsareknowforadministrationcostsaretypicallychargedbasedontheassetsundermanagementofthefundandrangebetween1to10basispointsofassetsundermanagement.Onebasispointisequalto0.01%.SoletstakeArbitrium’sfullydilutedvaluationwhichcurrentlyis$12BonCoinGeckoasametricforAUMandamidrangeoffeesso5BPSwhichgetsustoayearlyadminfeeof$6M,andthiswouldbeforacomplexhedgefundwithmanyinvestors,trades,andtotaltransactionsinthe1,000sto10,000speryear.

Asanoteadministrationfeeswouldinclude,investorcommunication,legalandcompliance,KYC,accountingandreportingandthefacilitationofpaymentsandexpenses.

Whyisthefoundationbudgeting3XthatofahedgefundforgeneralandadministrativefeeswhenitisnotnearlyascomplexasafundandthemoreimportitemssuchasR&DandTechnicalInfrastructureisassignedconsiderablyless?

Thenextquestionwouldbeiftheburnratewiththecurrentbudgetis$36Mperyearwhydoesthefoundationneed$1Bintokenallocationsinthefirstplace?Areasonableallocationwouldbecurrentbudgetadjustedforinflationtimesarunwayof5yearssoatmost$150mto$200m.

Ithinkthefoundationneedstopublishadetailedreportonthecostexpendituresofarandbreakdownthebudgetfortheyearandfutureyearsinmoredetail.Alistofalltheserviceprovidersengagedandtheprocessofhowtheywereengagedshouldalsobepublishedaswellashowtheseserviceprovidersperformancewillbeassessedandthecontractrenewalprocessgoingforwardandifthiswillbeputtoavoteformembers.

Infartoomanycasesweseeecosystemfundsdisappearingintoablackboxofexpenseswithnoaccountabilityoftheseexpensestothecommunityandassessmentifwhatthefoundationispayingisreasonableandfairandifthefoundationisbeingruneffectivelyandefficientlyinthebestinterestoftheecosystem.

InitscurrentformIcannotvoteforAIP1.1andwouldaskthefoundationtoproduceadetailedbudgetforthenext12month,alistofserviceprovidersandtheirfunctionandtojustifywhythegeneralandadminexpensesarebeingallocated45%ofthetotalbudget.

10


fred

1
Apr2023
(1)Whatdoescontrolmeanhere?IsthereawalletthatcollectstheETHmadeinfees?HowdoestheDAOcollectthisrevenue?IsitcurrentlygoingtoOffchainLabs?

Thesefundsaredirectlysenttothetreasurybytheprotocol-therearenointermediariesinthatprocess.It’spartofhowtheL2transactionexecutiongoes(likeintheL1partofthetxfeesgetburnt,intheL2partofthefeesgetsentdirectlytothetreasuryaddress)

(2)Ifthisisthefoundation’syearlyburnrate,andyou’dliketosecurea4-yearrunratefromtheDAO,assuming$ARBholdsitspricearound$1.20,adjustingforthe50millionalreadyspent,whatistheneedfortheadditional$796millionin$ARB?(50x1.2=60,36x4=144,1000-144-60=796).

Thesefundsallowthefoundationtobecompetitivewithotherfoundationswhenseeking/negotiatingpartnershipswithprojects/enterprises.
Manytimesthesenegotiationscan’tgointothepublicuntiltheyareagreedupon,butthefoundationwillmakethemavailablethroughtransparencyreportsoncethesedealsareoutinthepubliceye.
Alsonotethatthesefundsarelockedupandreleasedthroughoutthe4yearwindow,theDAOisabletocontroltoadjustthisunlockschedule.Itswhatsection(3)aroundEcosystemGrowthInitiativestalksabout.

(3)Whatdoesthismean?Theaskisfor750million$ARB.AreyousayingyouintendtoholdhalfandconverthalftoUSD?$ARBmightaswellstayintheDAOtreasuryifyoudon’tintendtospend.

SomeofthefoundationscostsaredenominatedinUSDterms,othersintokens.Forexample,operationalcosts(iestaplersfortheoffice)areusuallyindollars.ButwhenenteringapartnershipwithaprojecttohelpthemjointheArbitrumecosystemtheremightbeadollarpartbutalsoatokenparttothedeal.Inthesetokenpartsofthedealtheyusuallyalsohavelockupsbuiltintothem.IfthesefundsstayintheDAOtreasuryandnotinthefoundation’sbalancesheet,thenthefoundationisnotabletonegotiateandparticipateinthesedeals(asmentionedabovemanyofthemarerequiredtonotbeonthepubliceyeuntilagreedupon).
AlsoworthreiteratingthatallthesearesubjecttothevestingschedulecontrolledbytheDAO.

(4)Whathappensintheeventofabudgetoverrun?AsktheDAOformoremoneyagain?4yearsistoolongofatimehorizontofundfortheDAOtoassesswhetherornotthefoundationsinterestsalignwiththecommunityandecosystem.

Thatisagoodpointandpartofthereasonwhythereisavestinglockupschedule.Atthesametimehavingthefoundationwellcapitalisedforthecomingyearsisastrongsignalforbigpotentialpartners-theylikeknowingthattheirpartnersarecapitalisedandabletobearound4yearsfromnow.

1Reply
8


lindsey
Apr2023
ThisAIPproposesplacingthe7%outstandingdistributioninasmartcontract-controlledlockup–linearlyunlockingover4years–alongsidetransparencyreportstructurestoallowtheDAOtoperiodicallymonitorexpendituresandotheractivitiesoftheFoundation.

Thoughtherearelargertopicsbeingdiscussedhere,Isawthementionforsmartcontractstomanagea4yearlockupw/linearunlockingandwantedtosharetheHedgeytime-lockcontractsiftheyareusefulfordoingthisinatransparentway.

Ourtime-lockcontractsareusedbyGitcoin,Shapeshift,andothersandcanmanagethelinearunlockw/anycliff/unlockscheduleyouwant.Happytoalsomakeacommunitydashboardaswelltoallowanyonetoviewtheunlockschedule+amountclaimedw/reportinginrealtime.

Thiswouldallbeapublicgoodonourend.

1Reply
7


yunze7373
Apr2023
Itfeelsmuchmoredetailedthanbefore.Mademostoftheconcernsclear.btw,Iammoreinterestedinrecruitment.Whatarethe15positionsandinwhatform?

4


Danr831
Apr2023
Dowegettovoteonthis?

1Reply



fred

lindsey
Apr2023
Thankyoufortheanswer,doyoumeanthevestingcontractsincludedinhere5?Andhavetheybeenaudited?

1Reply
3


fred

Danr831
Apr2023
Yup,here’sthetimelinefromthepost

ThisAIP-1.1shallbepostedontheDAOforumandwillhaveatleasta72-hourperiodforDAOcommentsandinput.Aftertheendofthe72-hourperiodandappropriateupdatesincorporatingDAOfeedback,thisAIP-1.1willbepostedforvoteonSnapshotforanadditional7days.

4


zameer1020
Apr2023
thisisgreatworksupportwaiting

4


lindsey

fred
Apr2023
Forlinearunlockingthesearetherightcontracts.Andtheyhavebeenaudited-attachingthemostrecentaudithere8.

4


alaca
Apr2023
waitingforpassingtovote




John_P2P.org

2
Apr2023
(PostingonbehalfofP2P.org3)

Overall,wefindthisproposaltobemuchclearerandmoredetailedthanthepreviousone.Thisisaconsiderablestepintherightdirection,andwewanttocongratulatetheteamfortheiragileresponseindraftingthisnewproposal.Thatbeingsaid,wewouldstillliketoseesomefurtherimprovementsandclarifications.

Wedonothaveanymajorconcernsabouttheamountallocatedtotheadministrativebudget.Webelievethatawell-fundedandrobustDAOisnecessarytocompeteintherapidlydevelopingcryptoecosystem.Ourconcernsliemainlywiththelowleveloftransparencyandvaguenessonhowthebudgetspendingwillbereportedtothecommunity.

Wevoteyes.

1.SmartContractLockup

Althoughmanycommunitymembershavesuggestedimplementingalockupschedule,webelievethisisnottheidealsolution.Infact,itmaybeharmfulandcounterproductivetothegoalsofthisproposalandthedevelopmentoftheDAO,particularlywithregardtothesectionhighlightedbelow.

TheAdministrativeBudgetWalletwillbeusedforcoveringongoingadministrativeandoperationalcostsofTheArbitrumFoundation,paymentofserviceproviders,andforthepurposeoffosteringthegrowthanddevelopmentoftheArbitrumecosystem.

Alockupschedulemayonlyserveasa“feelgood”mechanism,whilealsolimitingsomeoftheFoundation’sstatedgoals.However,concernsabouthowtheFoundationhandlesspendingcouldbealleviatedthroughtheproperimplementationofTransparencyreports(moreonthatbelow).

2.OperatingBudget
Onceagainourconcernsherearenotwiththetotalbutwiththelackoftransparencyandvaguenessofeachbudgetcategory.

Toaddresstheseconcerns,itisidealtobreakdowneachbudgetcategoryintomoregranulardetail.Thiswillmakeiteasiertounderstandhowfundsarebeingallocatedandidentifyanypotentialdiscrepancies.Werecognizethattheremaybelimitationstodoingthisatthisstage,buttheseshouldbecommunicatedandthereasonsoutlined.Forreference,pleasecheckoutLido’sbudgetproposal8.

Thisoperatingbudgetpresentsbest-faithestimatesoftheFoundation’santicipatedbudgetaryneedswhichmaybesubjecttochange.

Furthermore,ifthebudgetwascreatedwithbest-faithestimates,itshouldbepossibletodescribetheprocessusedtodeterminethesevalues.Providingthislevelofdetailwillincreasetransparencyandaccountabilitywithinthebudgetingprocess,ensuringallstakeholdersareinformedandengagedintheFoundation’sfinancialdecisions.

3.EcosystemGrowthInitiatives

Nooppositiontotheuseoffundsforthispurposeaslongasproperoversightandtransparencyprotocolsareinplace.

4.TransparencyReports

Annualreportsandsemi-annualprogressupdatesarenotenough.Ifpossibleweshouldcreateareal-timeprogressreportingsystem.Thiscanbeverytime-consumingtobuildbutitcanbeoutsourcedtothecommunitywithagrant.Additionally,thiswouldbeagroundbreakingproposalthatwouldsetthestandardfortransparencyandaccountabilitynotonlyforDAOgovernancebutanytypeoforganization.Inthemeantime,werecommendthattheFoundationprovidequarterlyupdatesonbudgetspending,aswellasregularupdatesonanymajorinitiativesordevelopments.

ThiswillhelptobuildtrustandconfidencewiththecommunityandensurethattheFoundationisoperatinginthebestinterestsofallstakeholders.

WewouldliketoseeaproperlyformalizedreportforeachEcosystemGrowthInitiativesspendingconducted.Herearesomekeyelements:

AsettimelimitforthepresentationofatransparencyreportfollowingeachspecialgrantadmissionbytheFoundation.(60dayssoundlikeareasonableamountoftime)
Goalsofthegrant
ProposedOKRsusedtoevaluatethesuccessofeachgrant
1Reply
7


BlockworksResearch
Apr2023
BlockworksResearchwillvoteinfavorofAIP-1.1

Webelievetherevisionsaresatisfactorywithour“pathforward”suggestionsandthatthisproposalwillbeoverallbeneficialtotheDAOandprotocol.Ourmainrequestswerethatthefoundation:

Provideadetailedbudgetbreakdowntojustifythe750MARB.
CreateaDAO-controlledvestingcontractforthetokens.
Bothconditionshavebeenappropriatelymet.Aswehavealreadystated,webelieveaFoundationfocusedoncreatingavibrantandsustainableecosystemisadvantageoustothesuccessofArbitrum.Itisouropinionthatthe7.5%allocationisfair.Thoughwedonotforeseeitoccurring,wearehappytheDAOwillmaintaintheabilitytodiscontinuethestreamofthesefundsatanytimeifthenewlyintroducedbi-annualtransparencyreportsshowtheFoundationisnotmeetingitsKPIs.Additionally,weappreciatethedivisionoftheoriginalAIP-1intomoreeasilydigestibleanddiscussablesmallerinitiatives.

Whilewerecognizetheteam’smisstep,wealsocriticizetheresulting“witch-hunt”thathastakenoverthenarrativeoverthelastweek.TheBlockworksResearchteamremainsoptimisticaboutthefutureofArbitrum,andwelookforwardtobeingastewardinitscontinuedsuccess.

26


Augustus
Apr2023
Ihavefoundthispostratherconfusing.175MillionARBisgoingtobeunlockedofthe750Milliontaken(50millionspent),forthenext4years.Buttheoperatingbudgetis36million.Sotheremainingmoney,eachyeargoeswhere?

ThisismuchmoretransparentandopenthanIhaveeverseen,soIdosupportthis.Ijustfeellike129Millionextratokensisnotable.

1


_axtina

Lenny
Apr2023
Thisisafairlystandardsalaryforaseniorlevelengineeratatechcompany.Highlyspecializedengineeringfieldsareextremelycompetitivebecausetalentpoolislimitedandskillsettakesyearstodevelop.Therewouldbenoincentiveforsomeonetochooseajobbuildingtheprotocolvs.workingatGoogleifcomparablecompisnotonthetable.

1Reply



AlexNikulin
Apr2023
Ihopeeverythingiscleanhere.Otherwise,theremayberegulatoryproblemsinthefuture.




karelvuong
Apr2023
(PostingonbehalfofTreasureDAOasamemberofitsDAOcouncil-KarelVuong,Co-Founder.)

TreasureDAOwillvoteinfavourofAIP-1.1.

AsstatedinourresponsetoAIP-16,theissuefortheTreasurecommunitywasnevertheproposedsizeoftheAdministrativeBudgetWallet(ABW)nordidwehaveskepticismoverArbitrum’sintentioninrequestingthisamountofARB.Wevotednoandaskedforaresubmittedproposalwithmoredetailsaboutprogramtypes.OurrationalewasensuringthattheearliestproposalsenactedbyArbitrumDAOsetapositivemodelforfuturegovernance.WebelieveAIP-1.1createsagoodexampleforgovernancebestpracticesbyprovidingmoredetailsontheABW.

Webelieve$36millionisareasonableoperatingbudgetoverthenext12months.ArbitrumiscurrentlytheleadingL2andcompetingwithhighly-capitalizedorganizationstomaintainthisspot.Arbitrum’scompetitivenesshingesonfurtherdevelopmentofOne,Nova,andOrbit,extensivebusinessdevelopmenttobringinthebestprojects,continuedR&Dinaspacethatisrapidlyevolving,andsoon.

ThisproposalofferssufficientclarificationonthetypesofprogramsthatwouldbesupportedbytheABW.Giventhespeedatwhichtheindustryisevolving,requestingfurthergranularitythanprovidedherewouldbeunwiseasitprovidesbadfaithoruninformedactorsawaythroughgovernancetopreventtheFoundationfromadaptingallocationsasnecessarytoremaintechnologicallycompetitive.Aswestatedpreviously,thecommunityshouldnothavetoomuchinputintohowfundsareallocatedtowardstechnicalorprocurementprograms.HoldingARBdoesnotautomaticallyqualifyonetospeakupaboutthecostsorpracticalitiesofblockchaindevelopmentorevenserviceproviderrelationships.Moreover,thevestingclauseinthisproposalisasufficientsafeguardandanimprovementoverAIP-1.

10


moeen
Apr2023
Lookingforwardtothevoting,I’mgoingwithaFOR

1


ChainLinkGod
Apr2023
ChainLinkGodwillvoteinfavorforAIP-1.1.

Ioriginallymadefourpointsoffeedback2ontheoriginalAIP-1proposal,whichechoedmanyoftheconcernsothershadraised.Ibelievethesepointsoffeedbackhavebeenadequatelyaddressed.

SplittingUpTheProposals

TheoriginalomnibusstructureofAIP-1containedtoomanynon-contentiousandcontentiousitemspackagedtogetherintoasinglevote.WiththetransparencyreportontheinitialFoundationsetup,AIP-1.1focusedontheFoundation’s750Mallocation,andAIP-1.2focusedonamendments,thescopeofwhatthecommunityisvotingonisfarmoremanageableandsetsabetterprecedent.

AdministrativeBudgetWallet

IwasalwayssupportiveofthecreationandfundingoftheArbitrumFoundation,howeverfelttherewastoolittleinformationtohowtheassetsweregoingtobeused.ThebudgetproposedinthisproposallookstobereasonableandthetransparencyreportprovidedthemuchneededcontextontheFoundationdirectors’backgrounds.

ThesmartcontractenforcedvestingofFoundationfundsisalsoaniceaddition,providinggreateraccountabilityoverfundusage.WhileIbelievethevestingscheduletobetooconservative,creatingariskthattheFoundationmaymissoutonkeydeals,giventhattheFoundationcanproposetoacceleratevesting,andtheDAOhavingtheultimateabilitytochangethevestingspeed,Isupportthismove.

RetroactiveVoting

MybiggestconcernwithAIP-1washavingtheDAOvoteretroactivelyonactionsthathavealreadytakenplace.Therefore,I’malignedwiththedecisiontomoveinitialfoundationsetupdecisionstothetransparencyreportandhaveitoutofscopeofwhattheDAOisactuallyvotingon(futurevotescanalwaysbemadeonadditionalchanges).WhileIstillbelievetheoriginalcommunicationsaroundtheallotmentofthe750MARBanditspartialusagewaspoor,IdonotbelievetheFoundationhad/hasanymaliciousintent.IbelieveitisinthebestinterestsoftheArbitrumcommunitytomoveforwardandplacethefundsinthevestingsmartcontract,wheretheDAOhasoversight.

VotingThreshold

WillcommentonthisontheAIP-1.2proposal,TL;DRI’maligned.

8


Plutus
Apr2023
We’regladtoseethatthecommunity’sfeedbackhasbeentakenintoconsiderationinaverycomprehensivemanner!

Wefeelthattransparencythroughverifiableon-chainactions,encouragingsufficientfundingwithingoodreasonandtheemphasisonactualDAOgovernancepowerareallpresentinthisproposal,whereastheywereglaringlyabsentinAIP-1.Wewouldideallywanttoseemorediligentanddetailedbudgetingtransparencyforthefunds-asalsopointedoutbyourcommunitymemberssneddlesanddmetreeohs.Currentstructureisstillratherhigh-level,althoughanimprovementfromtheoriginalAIP.

Tous,AIP1.1and1.2representatransparentandhonestpresentationforsettinguptheFoundationanditskeyparameters,afterwhichwecanallgetbacktobuilding!

6


Lenny

_axtina
Apr2023
Yeawithvestedstockoptionsmaybe…




kishannazre
Apr2023
Theproposedamendmentsaresatisfactory.




cp287
Apr2023
Wearegladtoseethattheproposalsarebecomingmoretransparentandopen,andalreadycontainfarfewervotingquestions.WethinkthisisagreatstepintherightdirectionfortheformationoftheDAOanditsdescribedgoalsintheconstitution.
WealsorecognizetheneedfortheArbitrumFoundation,weagreewiththestatedgoalsofthefoundation,andwerecognizethatsignificantfundsareneededtobecompetitive.

Butwedohavesomecommentsandquestionsabouttheproposal.

OnMarch16,2023,theArbitrumnetworks(ArbitrumOneandArbitrumNova)weredecentralizedandgiventothenewlyformedArbitrumDAO.Includedinthistransitionwere:

Controloftheupgradeabilityandtechnicalfutureofthechains
ControlovertheDAOtreasury
Controlovernetfeerevenue-i.e.thenetdifferencebetweenfeescollectedbyon-chainoperationsandL1feespaidbytheSequencer
AllArbitrumsocialmediaplatformsandaccounts
Abilitytoelectand,ifdeemedappropriate,removetheSecurityCouncilandDirectors
…
Weabsolutelydisagreewiththisformulation.OnMarch16,therewasnotransitiontotheDAO,thearchitectureoftheDAOandthewaydecisionsaremadewereneverapprovedbyavote.

Goingoverthepoints:

Controloftheupgradeabilityandtechnicalfutureofthechains-Itisfalse.RightnowtheArbitrumDAOhasnoaccesstothekeysthatallowyoutoupgradeormodifychains.

ControlovertheDAOtreasury-Itisfalse,we’veallseenthatthroughthetwotransaction,where40Mand10MARBweremadeonMarch21and24respectivelywithoutanyapprovalfromtheDAO.

AllArbitrumsocialmediaplatformsandaccounts-Asfaraswe’reconcernedit’safalse.Atthispoint,theadminrightsofneithertwitter,discordnortelegramhavebeentransferredtoanydegreetotheDAOasfarasIknow.AtleastTwittercontinuestotweetwithoutanyDAOapproval,anddiscordadministratorshavenotchangedandareunderthecontrolofOffchainLabs.

Abilitytoelectand,ifdeemedappropriate,removetheSecurityCouncilandDirectors-It’safalse.DespitetheproceduredescribedinAIP-1forselectingsecuritycouncilmembersinthefuture,alsoinAIP-1wewereaskednottoletthefirstsecuritycouncilmembersbeselected,butalreadyaskedtoratifythedecisionalreadymade.

Despitethegeneralagreementwiththeproposal,wefinditanotherdangerousprecedenttovoteFORtheproposalwhenitcontainssuchblatantfalsehoods,andavoteinfavorcouldbeseenasagreeingthatitistrue.

Oursuggestion:Removetheseparagraphsentirelyfromtheproposal.

AboutOperatingBudget
Whileweareawareofthehighcostoflegalservices,asaresomeoftheotherdelegateswefinditoddtoseesuchhighcostsinthe“GeneralandAdministrative”category,andwouldliketoseeabreakdownofthecategoriesintomoredetail.Wereallyfindthisdescriptionwiththelackoftransparencyandvaguenessofeachbudgetcategory.

Also,weareopposedtothebureaucraticcategoryof“GeneralandAdministrative”beinglargerthanthesumofthe“R&D”and“TechnicalInfrastructure”categories,asthisinourviewcontradictsthestatedprioritiesoftheFoundation.

Thus,wesuggesteitherreducingthesizeof“GeneralandAdministrative”,or,ifthisisnotpossible(whichwewillseeinamoredetailedcategories),increasingtheamountallocatedtoR&D.

TransparencyReports
Annualandsemi-annualprogressreportsarenotenough.Wealsobelievethatgiventheenormouscostoftheadministrativecostscategory,reportsshouldbemadeasoftenaspossible,ideallyinrealtime,butthemaximumacceptableperiodforsuchreportsshouldnotexceed3months(aquarter).

ExchangeofARBtoUSD
GiventhedescribedneedtopayforservicesindollarsratherthaninARB,webelievethatitisnecessarytodescribeinmoredetailthegeneralprinciplesoftheprocedure,responsibilities,terms,etc.fortheexchangeofARBtokensfordollars.Weunderstandthatthisinformationcannotbecompletelyopen,soasnottohaveaproblemwithdifferenttypeofattacks,suchasfrontrunandothers,butwebelievethatDAOneedtoknowthegeneralrulesandprinciplesofthisprocedure.

Conclusion:aswedescribedabove,wefindthisproposaltobewell-developedandhaveonlyminorchangesandmoredetails.WewouldbewillingtovoteFORifitwerenotfortheproblemswedescribedinthefirstpoint.

GiventheacceptanceofourvoteFORasaratificationofthefalse,weareforcedtovote“Abstain”forthisproposal.

1Reply
3


sokos
Apr2023
TRUSTisthebedrockofanyorganisation.COMMONGOALSisthemotivatorbehindtheactionsofeachoneinArbitrum.Nomatterwhattheusecasesmaybe,nomatterhowbreakthroughorincrementalouruniqueideastoimprovetheblockchainecosystemis,itisimperativethatwefollowcommonestablishedpracticesandpromotetransparencyandconsensus.
Thelong-termsuccessoftheprojectcannotbecomevictimtoshort-termneedsofagroupofpeople,orfluctuationsinthecryptoindustry.Let’sputall$ARBbackinourpiggybankandrespectthelongtermvalueitofferstomillionsofretailandcorporatestakeholders.
Thankyou.

1


BlockworksResearch
Apr2023
BlockworksResearchhasputAIP-1.1liveonSnapshot:
https://snapshot.org/#/arbitrumfoundation.eth/proposal/0x7203289844e807781e8d2ec110d4b97a79a29944cae06a52dbe315a16381a2ae33

1Reply
5


limes

fred
Apr2023
Thankyoufortheclarificationonthesequencerfees!

I’mnotsurethatbeingcompetitivewithotherfoundationsbankrollsshouldbethegoalhere,butratheraninternallyderivednumberthatthearbitrumfoundationwouldliketospendonstrategicpartnershipsinthecomingyears.

Toclarify,IwanttosupporttheArbitrumFoundationsstrategicpartnershipinitiativestoareasonabledegreeasthearbitrumfoundationisthebestpositionedteamtodosoandhaveshownabilitytoexecutewell.

However,itlooksasif$800millionisallocatedtothisover4yearsandIjustdon’tthinkthatcouldbeeffectivelydistributedinthebestinterestofthe$ARBholders.

3


Cynic
Apr2023
Theoperatorshouldreturnthetokensandthenre-proposetheproposal,soastocomplywiththelegalityoftheprocedureandrespectforjustice;insteadofaddingregulationstothetokensthathavebeenillegallytransferredasitisnow.




krst
Apr2023
AtL2BEAT,wehaven’tmadeourdecisionyetabouthowwearegoingtovoteonAIP-1.1.WeareleaningtowardsvotingFOR,butwe’dliketohavemorediscussionaroundit.We’llbehavingacommunitycallonWednesday,12.04at12PMET,16:00UTC.Weencourageallinterestedparties,especiallythosewhohavedelegatedtheirtokenstoL2BEAT,tojointhediscussion;we’llgothrougheachAIPcurrentlybeingdiscussedandwillexplainhowwearegoingtovoteandthereasoningbehindourdecisions.

Wewillpostthelinktothediscussionlaterinthisthread(we’restillconsideringwhichplatformtouse),andwewillalsopostashortsummaryofthediscussionhereafterwards.

Asforthisproposal,wegenerallylikethepresentedapproach.

1.SmartContractLockup
Wedefinitelysupporttheideaofhavingthe“AdministrativeBudgetWallet”fundslockedinavestingvaultcontrolledbytheDAO.Inouropinion,thisservestwopurposes:

ItprovidestheFoundationwithasignificantbudget,positioningitwellintheblockchainlandscapeagainstsimilarorganizationsbehindotherchains.
ItgrantstheDAOauthorityoverthesefunds,allowingtheDAOtoclawbackthemifnecessary.
However,wewouldliketonotethatit’simpossibletoassesshowthissolutionwillworkinpracticerightnow,astherearenodetailsaboutthesmartcontractsforthesaidvestingvaultanditsconfigurationparameters.Ideally,itwouldbebesttoknowthosedetails(oratleastsomebroadtechnicalvision)beforethevotehappens.

2.OperatingBudget
Wesupportthisoverallbudgetstructure,althoughweechosomeothercommenters’remarksthatitcouldhavebeenabitmoredetailed.Wethinkit’sagoodstartingpoint,andweshouldworktogetherwiththeFoundationtoestablishanexpectedlevelofbudgetingdetailsforthefuture.

3.EcosystemGrowthInitiatives
WesupporttheideaoftheFoundationhavingadedicatedbudgetforsponsoringecosystemgrowthinitiatives.Inouropinion,thiscouldbemirroredbyasimilargrantsprogramrunbytheDAOinamoreopenandtransparentashion.However,thisshouldbeasubjectofseparatedebate.

4.TransparencyReports
WesupporttheplantoprovidetransparencytotheFoundation’soperationthroughTransparencyReports.Wethinkthatthefirsttransparencyreportthathasbeenpresentedisagoodstartingpoint,althoughwebelievethatinthefuturetheinformationpresentedtherecouldbemoredetailed.Thestructureandscopeoffuturetransparencyreportsshouldbediscussedwiththecommunityandoutlinedlateron.

Thatbeingsaid,we’restillopentodiscussingalloftheseissues.Weencourageallofyoutojoinusforthecommunitycallifyouthinkwe’remissingsomething.

2Replies
5


Orogodongo

1

Arbitrum
Apr2023
Ithinkitwouldbeabouttimetobringmoreclarityandtransparencywhenitcomestotheconceptofbusinessethicsbasedonthisstatement:

TheDAOisalsotaskedwithfosteringanddevelopingtheArbitrumecosystem,wheretheDAOmayseektopartnerwithcompaniesororganizationsthateithercannotorwillnotpubliclynegotiatecollaborationsorpartnershipsduetoconfidentialityandotheroperationalrequirements.Often,largeenterprisesnegotiatepartnershipopportunitiesinprivatewithoutpublicprocesses,wheretheserelationshipscanonlybedisclosedaftertheyareagreedupon.Havingawell-fundedFoundationempoweredtorepresenttheDAOinthisarena,alongsidepeerfoundations,isinthebestinterestsoftheDAOtofurtherdevelopthegrowthoftheArbitrumecosystem.

Itmightbethatthebetterwayforwardwouldbetodemandmoreopennesswithinsomekindofsetcircumstancestooptimizedecisionmakingforthebenefitofall.
AlthoughIcomprehendthefundamentalsofcompetitionandconfidentiality,butitcanbeoptimaltoproceedwithnewstrategiesfortheneweraofopensourceinformationandcollaboration.Intheend,weareallinthesameboatandweliveinaworldofabundance.

1


thinkDecade
Apr2023
Lookinggood.Itayesfromme.

1


GFXlabs

2
Apr2023
OperatingBudget	
Cost($USD)
GeneralandAdministrative	$16,000,000
R&D	$9,000,000
TechnicalInfrastructure	$5,000,000
Events,Marketing&Communications	$6,000,000
Total-NextTwelveMonths	$36,000,000
(50%$USD/50%$ARB)
*TheGeneralandAdministrativeline-itemincludespersonnel,contractors,legal,insuranceandotheroperationalcosts.AsofthedateofthisAIP,theFoundationcurrentlyhasfivefull-timecontributors,8contractors,andtheSecurityCouncilengagedtosupporttheArbitrumecosystem.TheFoundation’sbudgetanticipatestheneedtohireanadditional15full-timecontributorsacrosstechnical,growthandcommunityfunctionsoverthecourseofthisyear.

Thisoperatingbudgetpresentsbest-faithestimatesoftheFoundation’santicipatedbudgetaryneedswhichmaybesubjecttochange.

Cansomeonewiththeknowledgeprovidesomeinsightintothis?Thisbudgetappearsinexplicablylarge.

Whatwillthese20fulltimepeople(pluscontractors)beworkingon?

Thisisdifficulttosupportwithoutfurtherdetails.

3


brianfakhoury
Apr2023
I’mhappytoseethehoneststepstakenheretoimproveonthevalidcriticismonAIP1.Ultimately,thetwosalientpointsthatleadmetovoteForAIP1.1are:

Theimplementationofasmartcontract-basedlinearunlockoftheadministrativebudget.While4yearsisfairlyarbitraryandseemstobetakenfromprivatetokensalenorms,Ithinkitwillworkwellhere.Also,giventhebudgetbreakdownisanupperboundestimateinbestfaith,Iexpectleftovertokenstobere-allocatedtoafuturecontractfordistributiontothefoundationand/oranotherentitytofurthertheArbitrummission.
Transparencyreportsthatactasahealthcheckonregularscheduletoensuretheadministrativebudgetisbeingusedappropriately.Giventhecleanandopenformatoftheinitialreport2,I’mconfidentthesefuturereportswillappeasethecommunity.
Again,I’llbevotingFor.I’llalsobewatchingtoseethatexcesstokensfromthevestingschedulearenotallocateddiscretionarily,butrathertoacommunity-approvedcontract.

2


krst

krst
Apr2023
Heyall,wewillbedoingourcommunitycalltodayat12PMET,16:00UTConGoogleMeetup:


meet.google.com
GoogleMeet:OnlineVideoMeetingsandCalls|GoogleWorkspace1
UseGoogleMeettostayconnectedwithvideomeetingsandcalling(poweredbyGoogleDuo),partofGoogleWorkspace.

WewillbegoingthroughtheAIPsunderdiscussionrightnow,wewelcomeallcommunitymembersandotherdelegatestojointhediscussionandshareyourviews!

3


erysup
Apr2023
IwanttothanktheArbitrumteamforconsideringcommunityfeedbackandupdatingtheAIPtomakeitmoretransparent.It’sapositivestepforwardfortheFoundation.




sokos

1
Apr2023
Isn’titfunnythatmultimilliondollarendeavorsarehiddenbehindaliases?
WhospeaksfortheFoundation?Whoarethesefull-timeemployees?

Andunlessyou’rebuildingmedicalfacilitiesforanewvaccine,Icannotfathomhow$9MwillbespentinR&D.Certainlyveryworriedthatadministrativeisevenhigher…

Cryptowillnevermeetinvestor-gradeinterestifwekeepplayinghide-nseek.




mcfly
Apr2023
Thanks@Arbitrumforputtingthattogether.Itseemsimportanttoknowthesharerepresentedbythecompensationof20FTEforthenexttwelvesmonths.




yabirgb
Apr2023
I’mvotinginfavorofthisproposal.Therehasbeenagoodeffortontransparencyandnowthereisamuchbetterdefinitiononhowthetokenswillbeused.Finallyoneofmybiggestconcerns,howthedistributionwillbemadehasbeenclearedalongtheroadmapforgrowingtheteam

2


krst
Apr2023
L2BEATvotesFORAIP-1.1intheSnapshottemperaturecheck.

WehavecarefullyexaminedtheimplicationsoftheproposalandengagedindiscussionswiththecommunityduringtheGovernanceCommunityCall.Althoughwehavesomereservationsaboutthisproposal(listedbelow),wearevotinginfavorofitbecausewebelieveitisastepintherightdirectionthatcanbefollowedbyfurtherimprovements.Belowareourremarks:

Pros:

CreatesmorecertaintyaroundtheFoundation’s750MARBandproposestolockfundsinthevestingvaultfor4yearswithcontinuousvestingschedule
PromisestotransfertheownershipofthesefundstotheDAO(throughtheownershipofthisvestingvault)
Givessomeclarityaroundtheoperationalbudget
Promisesannualtransparencyreportsandsemi-annualprogressreporst
Cons:

Thesmartcontractcodeandconfigurationareunknownatthetimeoftheproposal,makingit,inpractice,avotetograntamandatetotheFoundationtolockthosefundsratherthananactualvotetoexecutesomethingon-chain.Inthiscase,wegivetheteamthebenefitofthedoubt,butinthefuture,wewillnotvoteinfavorofproposalslackingcleartechnicaldetailsor,attheveryleast,adetailedtechnicalvisionpresentedupfrontintheproposal.
Theoperatingbudgetessentiallyconsistsofafour-itemplandetailinghowtoallocate$36million,withoutprovidinganybackgroundinformationorspecifics.Althoughwedonotwishtoescalatethisissuerightnow,understandingthattheteamneededtodeviseaplanquicklyanddidnotwanttodelveintothedetails,thisapproachcannotbefollowedinthefuture.Ourconcernsarisenotonlyfromthesubstantialfiguresinvolvedbutmoreimportantly,fromthelackofclarityand,presumably,theabsenceofawell-definedplan.
Thesameappliestothetransparencyreport-itisnotparticularlytransparent,asthereisanabundanceoftextdescribingthesituationbutnotmanydetailsorconcretefigures.Whilethiscanbeunderstoodgiventhecircumstances,itcannotbethecaseinthefuture.
WeacknowledgethatthecurrentsituationisuniqueandtheFoundationrequiresformalapprovaltoproceedfollowingtherejectionoftheAIP-1proposal.However,wewishtoemphasizethatinthefuture,weexpectgreaterclarityandmorecomprehensivereportingfromtheFoundationconcerningtheDAOTreasuryusage.

3


tnorm

1
Apr2023
HiAll,

TraverfromtheMessariGovernor3teamhere.Greattoseeanincreaseintransparency,whichisanimprovementovermanyFoundationsincryptotoday.Asthevotestandscurrently,itappearsAIP1.1willpass.

AstheFoundationproceeds,we’dliketohelpexpandthecritiquesoftheFoundationintosomeproactivesolutionsthatcanimprovetheArbitrumFoundation’scommunicationwiththeDAO.

OperationBudget
Weagreewith@jason3sthattheoperationalcosts($36Mover12months)requiregreatertransparencywhichshouldbeaprerequisitefordistributinganyDAOfundstoanyassociatedFoundation.TheArbitrumFoundation’sresponsibilitiesbreakthemoldofmanycomparablefoundations(whichusuallyfunctionasafinancialandlegalwrapperfortheDAO,overseeoperations,anddistributefunding).

DAO	Foundation	Funding	OpsFunding(Annual)	FTE	Scope
Uniswap	UniswapFoundation	$74M	$4.67M	14	DistributeGrantsandadvocatefortheprotocol.
Balancer	BalancerFoundation	$500K	$500K	4	Manageserviceprovidersandfinancialmaintenancecosts.
Starknet	StarknetFoundation	50%Tokens	N/A	N/A	MaintainingStarkNetasapublicgood,continuednetworkdevelopment,anddevelopers’support.
Optimism	OptimismFoundation	30%Tokens	N/A	N/A	Legalwrapperandearly-governancesteward,allocatoroftreasuryassetstofundpublicgoods.
TheArbitrumFoundation’sscopeexpandstoincluderesponsibilitiesforoperatingArbitrum’srollups,including“operations,blockchainoperation,infrastructure,servicecontracts,andongoingimprovementstotheArbitrumecosystem.”Further,theinitialbudgetincludes$9Mforresearchalone.Understandingthescopeofwork(SoW)fortheFoundation’stechnicaldevelopmentandoperationsassignmentswouldbevaluable,consideringthisisgenerallyoutsideatypicalFoundation’spurview.Inmostcases,R&Disdonebyaseparatelabsteam(OptimismLabs,UniswapLabs,etc.)orotherwisesupplementedbygrants.IfbothOffchainLabsandtheArbitrumFoundationconductR&D,clarifyingeachresearchteam’sspecificoverlapandobjectiveswouldaligntheDAOwiththeaskandevenhelpjustifythebudget.

TheDAOwouldbenefitfromtheopinionofotherswithmoreDAObudgetingexperience(re:@gfxlabs)onevaluatingthisframework,giventheFoundation’sscope.However,wenotethevoteofconfidencefromdelegatessuchas@karelvuongand@krst.

EcosystemGrowthInitiatives
Theecosystemgrowthinitiativealsoneedstobemorespecific.Tobeclear,we’renotagainstthedelegateddistributionofgrantsfundingtotheFoundation,anddelegatedgrantsprogramswillpresumablybeamoreeffectivestrategythantoken-votingduetovoterfatigue,varyingstakeholderinterests,andnear-termbiases.Thatbeingsaid,itmustbepairedwith:

AclearindicationofthemethodtheFoundationwilluseforgrantdecisions;

Theprocessforgrantselection;

TheKPIsandgoalsgranteeswillbeheldtoo;

Infrastructuretotracktheaccountabilityofgrantees;

Theamountandscheduleoffunddistribution(ratherthanjustamentionofthefactthatthesewillexist).

TheMissionStatementintheFoundation’sbylawshighlightsthevariednatureoftheopportunitiestheFoundationintendstopursueandasetofKPIsthatcantrackalloftheseopportunitiesbeingdeveloped.

TheKPIsreferencedinthebylawsshouldbeexpandeddramatically.SeeOptimism’srecentlyrevampedeffortshere1fortheirincentiveprogram(launchedafterbacklashfollowingthemisallocationoffundsandthemisuseofallocatedfunds).

Grantscanbeanespeciallyperniciousavenueforfavoritism,corruption,andmisallocation.TheDAOshouldsolicitgreatertransparencyaroundFoundationdistributionsandsethighstandardsformeasuringtheROIandimpactofdistributedgrants.

TransparencyReports
4.TransparencyReports

WesupporttheplantoprovidetransparencytotheFoundation’soperationthroughTransparencyReports.Wethinkthatthefirsttransparencyreportthathasbeenpresentedisagoodstartingpoint,althoughwebelievethatinthefuturetheinformationpresentedtherecouldbemoredetailed.Thestructureandscopeoffuturetransparencyreportsshouldbediscussedwiththecommunityandoutlinedlateron.

3.TransparencyReports

Annualandsemi-annualprogressreportsarenotenough.Wealsobelievethatgiventheenormouscostoftheadministrativecostscategory,reportsshouldbemadeasoftenaspossible,ideallyinrealtime,butthemaximumacceptableperiodforsuchreportsshouldnotexceed3months(aquarter).

4.TransparencyReports

Annualreportsandsemi-annualprogressupdatesarenotenough.Ifpossibleweshouldcreateareal-timeprogressreportingsystem.Thiscanbeverytime-consumingtobuildbutitcanbeoutsourcedtothecommunitywithagrant.Additionally,thiswouldbeagroundbreakingproposalthatwouldsetthestandardfortransparencyandaccountabilitynotonlyforDAOgovernancebutanytypeoforganization.Inthemeantime,werecommendthattheFoundationprovidequarterlyupdatesonbudgetspending,aswellasregularupdatesonanymajorinitiativesordevelopments.

TransparencyReportsshouldincludeestimatingtheroles/titlestheFoundationaimstoemployalongwiththeirassociatedpersonnelcosts,articulatingtheamountoffundingdedicatedtoR&Dinitiativesandtheirobjectives,andamoregranularbudgetbreakdownformarketingcampaignsandeventsbudgets.Inaddition,theFoundationshouldbeabletosharefixedoverheadcostsfortechnicalandnon-technicaloperations.Thetransparencyreportsshouldresemblemorenumbersandlesstext,akintoaspendingauditwithspecificlineitemsandinitiatives(beyondasingle$9Mchunkoffunding).Whilereal-timereportingmaybetooheavyalift,Idon’tseeanyreasonnottopublishonaquarterlybasis(ataminimum).

Further,thesedetailsinformhowtheDAOcanapproachitsroleinoperatingaroundtheFoundation’sinitiatives.AsproposalsexplorenewfundingavenuesfortheDAO,theclearertheFoundationcanarticulateitsscope,themorehelpfultheDAOcanbeinachievingourcollectivegoals:slightly_smiling_face:

Lastly,we’dexpecttheDAOtopursueafurtherproposaltodefinefuturetransparencyandreportingstandardsfortheFoundationtoabideby.We’rehappytocollaboratewiththeFoundationandtheDAOtosetanagreeableandprofessionalstandard.

13


cattin

3
Apr2023
Helloeveryone,

OnThursday131wehadour2ndgovernancecallatSEEDLatam2incollaborationwithL2enEspañol1wherewediscussedwithourcommunitytheongoingproposals:

AIP-1.05-Return700M$ARBtotheDAOTreasury2
AIP-1.1-Lockup,Budget,Transparency
AIP-1.2-FoundationandDAOGovernance2
Participants:60attendees1

Duration:1h

Ourvotingprocedure
Truetoourethos,wewentthrougheachproposalandexplainedthemindetailtoourcommunity.Thenthedebatewasopenedforcommunitymemberstoexpresstheiropinionsoneachproposal.Finally,eachproposalwasvotedonindividuallybycommunitymemberspresentinourdiscord1.

Directcollaborators@axlvaz_SEEDLATAM.eth@Manugotsu_SEEDLatam@SEED_Latam_Joxes@Phenrril@MCamereand@Noaalsoexpressedtheiropinions.Wewanttothanktheregionaldelegates,@ArbiGod.eth,whojoinedthedebateandcontributedtheiropinions.

Asalways,anymemberofthisDAOwhowantstoparticipateinourgovernancecallsandisopentodiscussingArbitrum-relatedissuesismorethanwelcome.

About:AIP-1.1-Lockup,Budget,Transparency
Ourvoteisinfavor5.

Rationale
AIP-1.1addressesandresolvesmostoftherequestswemadepreviously.However,despiteourfavorablevote,wewanttoexpresstheopinionofourcommunityoneachpoint.

AboutSmartContractLockup
Webelieveitisawisedecisiontolockfundsinasmartcontract.ItalsorestoresDAOcontroloverfundsbyallowingadjustmentstofuturefundingand/ormodifyingtheunlockschedule.

AboutOperatingBudget
Thecommunitywassatisfiedwiththepresentationanddescriptionoftheoperatingbudget.However,theyexpressedadesireforfuturebudgetstobemoredetailedintermsofexpensesandalignedwiththegoalsoftheArbitrumFoundationandArbitrumDAO.

AboutEcosystemGrowthInitiatives
Inthispoint,wehadrequestedmoredetailsinthepreviousproposal.Webelievethefocusandobjectivesforgrowthinitiativesarebetterclarified.Althoughtheapplicationandapprovalprocessstillneedsdetailing,SEEDLatamandL2enEspañolareavailabletocollaborateinthedevelopmentoftheseprocesses,consideringtheexperienceofsomeofourmembersinsuchinitiatives.

TransparencyReports
Ourcommunitywasmorethansatisfiedwiththistransparencyreport,whichprovidesadescriptionofTheArbitrumFoundationdirectorsanddetailstheinitialcostsofestablishingTheArbitrumFoundationandArbitrumDAO.However,therelationshipwithOffChainLabsandtheselectioncriteriafortheNovaNetworkDataAvailabilityCommitteeremainsabitobscure.

Conclusion
Althoughsomepointsstillneedclarification,AIP-1.1mostlyresolvesallpreviouslyexpresseddoubts,andthisisnotanimpedimenttovotinginfavor.OurcommunitybelievesitistimeforArbitrumtotakethenextstep,andforthem,theofficiallaunchoftheFoundationisessential.

AbouttheotherProposals
Ourvotingandopinionon:AIP-1.2-FoundationandDAOGovernance3
Ourvoteandopinionon:AIP-1.05-Return700M$ARBtotheDAOTreasury5
1Reply
6


taka0157
Apr2023
Verynicecontent.
I’mlookingforwardtothefuture.

1


arbit

cattin
Apr2023
StayingtunedfortheexcitingprogressofAIP-1.1implementationandwitnesshowourvibrantcommunity’svaluablefeedbackcontinuestoinfluencethefuturedirectionoftheArbitrumFoundationandDAOgovernance

2


Bob-Rossi
Apr2023
Ihavevoted“For”onAIP-1.1.TherearesomeitemsIdisagreewith(moredetailbelow),howevermyvoteisonethatismorebasedonwantingtolookpasttheinitialissuesonAIP1andtojustlookatthesubstance.Basedpurelyonsaidsubstance,Ibelievethisislargelyagoodproposalandisrelativelyin-linewithfundingdecisionsofotherDAOswithinthisspace.MydisagreementsarerelativelyminortothescopeoftheAIP,sovotingagainstwiththeasktokeeprevisitinguntilheAIPisperfectwilljustresultinunnecessarydelays.Itreallyisasituationof“Don’tletPerfectbetheenemyofGood”,forbetterorworse.

Ibelievetherehasbeengoodstepstakentowardstransparency,howeverIbelievethereshouldhavebeenmoreprovidedandwouldbehesitanttovoteforsomethingthisvagueinthefuture.Herearesomesuggestionsforthefuture,ideallytobeexpandeduponinfurthercommunications:

Theoperatingbudgetisanicebreakdown,butitisveryhigh-levelandlacksdetailonwheretheUSDiscomingfrom(assumingARBsales,butlacksdirectiononhowthatwillbeexecuted).I’dliketoseemoreexpandedonhere.

Itisadifficult,nearimpossible,thingtodoconsideringpriceswings…butwiththepriceofARBfluctuatingbetween$1toover$1.50recentlythereisaprettylargegapintheamountofcapitalprovidedandtheoperatingbudget.ObviouslyEcosystemGrowthInitiativeswillfillalotofthatin,butevenat$1ARByouarelookingat$139Millionayearbeingallocatedwithnorealplans.Thiswillonlybecomemorenoticeableifthepriceappreciates.I’mnotaskinganyonetopredictthefuture,butthereshouldbesomemoredetailonwhattheplanisintheeventofthatallocatedamountfarexceedingexpectations.Ifitissimplymoremoneyforpublicgoods-great!Ormaybepartofthatisear-markedforoperations5+yearsout…?Whateveritendsupbeing,itshouldbealittlemoreclear(andasnotedabove,notesonhowtheUSDwillbeacquiredwouldhelphere).

Transparencyreportsflatoutneedtobequarterly.Yearlyisfartoolong.Semi-annualIcouldmakeacasefor,buttheinitialissueswithAIP-1theleewayforthatisnolongerthereinmyopinion.I’llalsoaddthatifthetransparencyreportswillmimicthestyleofthefirstone,theywillneedmoredetailinthem.

2


nguyencuong
Apr2023
thiswillbeoneofthestepstotaketheprojectfurther,anddevelopmoresustainably,withalargecommunityliketodayfortheproject,whichisalargenumberofuserssupportingtheproject.GreatLFG:rocket::rocket::rocket:




gauntlet
Apr2023
GauntletissupportiveofAIP-1.1.

Weappreciatethereceptiontothecommunity’sfeedbackandtheeffortputintothisproposal.Theproposedstructurearoundtokenlockupandtransparencyalignswithsimilarconstructsthathaveworkedelsewhere.Furthermore,weapproveoftheproposedoperatingbudget,asthetransparencyreportwillallowtheDAOtoholdtheFoundationaccountableforexpenditures.

WealsoagreethattheFoundationplaysakeyrolewithregardstosourcing,negotiating,andonboardingcertainvendorrelationships.Tofurtherreduceambiguityaroundthispoint,wewouldwelcomeadecisionframeworktomakeitcleartothecommunitywheneithertheFoundationortheDAOshouldberesponsiblehere.Lastly,astheFoundationwillbemadeupofpeopleclosetotheArbitrumecosystem,wesupporttheproposedplanforecosystemgrowthinitiatives.

Overall,wearepleasedtoseethechangesimplementedinAIP-1.1andareexcitedforthingstomoveforward.

8


cryptopia

1
Apr2023
Iamhappytoseethateverycareisbeingtakentoensurethesecurity,stabilityandgrowthofthisproject.HoweverIdoshare@krstconcernsaboutthelackofspecificdetailsonhowthisproposalisgoingtobecarriedout.ItisbecauseofhisprosandconsanalysisofthisproposalthatIfeelconfidenttovoteyesonit.

Ihopethattheteamwilladdresstheconcernsthat@krstand@Bob-Rossihaveraisedaboutthisproposalandthatwewillstartseeingmuchmoredetailedproposalsbeingputupforavoteinthefuture.Ialsoagreethattransparencyreportsneedtobepostedquarterly.Thiswayeveryoneiskeptintheknowaboutwhattheteamisdoingandcanmakeproposalsthattheybelievewillresolveanyissuesthattheysee.

Ifthisprojectisgoingtosurvivethisvolatilemarketweneedtoknowwhatchallengestheteamarefacingassoonaspossiblesothatasagroupwecanproposeandvoteonthebestsolutionstoovercomethem.

3


bakgwei
Apr2023
Iappreciatethereworkforthisoneaswell-andjustcastmyvote.

2


nguyentuhoangliem
Apr2023
Mateyoucan’tjustdividetheentireGeneralandAdminbudgetbyheadcount,itincludeswaymorethanjustsalaries-theyevensayitincludesinsurance,legalandotheroperatingcostsrightinthepost.

Byyourlogic,everyemployeeatWendysmustbemakinglike$200k

1


Pekosta
Apr2023
goodiniciativeisgreatfortheproject

2


Octavio
Apr2023
Thisisagreatsteptoabrighterfuturefor#ARB.Letsgooooo

1


Oxytocin
Apr2023
WiththeSnapshottemperaturecheckpassingalittleoveraweekago,Iwaswonderingif/whenthisproposalwouldmoveontotally.BothAIP1.1and1.2seemtohavepassedwithoverwhelminglypositiveresults,soIthinkwe’rereadyfortherealonchainvotewithnomoremajorrevisions!

1Reply
3

16dayslater

Damboy
May2023
Thelockupmechanismandgradualreleaseoftokensovertimeensurearesponsibleapproachtomanagingthefunds.Thetransparencyreportswillbecrucialinbuildingtrustandensuringthefundsareutilizedinthebestinterestofthecommunity.It’sgreattoseeafocusonecosystemgrowthandstrategicpartnershipsaswell.Overall,thisproposaldemonstratesacommitmenttotransparency,accountability,andresponsiblefinancialmanagement.




theenlightened

Oxytocin
May2023
@ArbitrumwhatisgoingonwithArbitrumFoundation?Thisdeafeningsilencecouldcausedisinterest.Whatistheissueexactly?Atleastcommunicatewiththecommunity.

Pleaseattendtothequestionabove

1

18dayslater

fred
Jun2023
TheengineeringforthisproposalisnowcompleteandavailableatArbitrumFoundation/governancePR#4416

ThisincludesthecodeforthelockupcontractaswellasanauditreportforitTrailofBitsAuditReport4.

Thisshouldbegoingliveforavotesoon,butwantedtofirstshareitfordiscussion.

2


fred

1
Jun2023
Itisnowliveforanon-chainvoteTally|ArbitrumProposal34

Editedupdate:
Thepreviousproposalwasmisconfigured,thecorrectlysetuponecanbeviewedatTally|ArbitrumProposal16

1


Griff
Jun2023
iseeasecondvoteisgoingupforthis…soweshouldjustignorethefirstvoteright?

3


Goodo
Jun2023
yes,thatseemslikeareasonableproposition.

3


Goodo

niklas67
Jun2023
Didyoureadthelaterexplanationsofthewholesituation.

5

8dayslater

zeydrm
Jun2023
SoI’mconsideredabouttheBudgetPlan.Asyousaidremaining7%ofARBtokenswillbereleasedliketotalofxmilliontokensovereachfor4yearsbutinthementionedplanitsjustconcernsonly36m?Noinformationhasbeengivenaboutwhatwillhappentotherest.IhopeArbitrumwillclarifiesthis.

5


ITUblockchain
Jun2023
Firstofall,wewouldliketothankArbitrumforupdatingAIP1.1andmakingtheconfusingexplanationclearabouttimestampsinthevestingsmartcontractandbudgetallocationtransparencypreviouslystated.Theupdatealsoclarifiedthequestionsofdelegatorswhostayedabstainforthesereasons.Moreover,thereareafewpointswewouldliketomakeconcerningtheproposal.

1.SmartContractLockup

WebelievethathavingcontroloverthebudgetandeasyaccesstofundsinanemergencyarecriticalfortheDAO.Withthisplanning,webelievethatspreadingthetokenlocksovertimeisthebestoption.Asanoutcome,thecommunity’strustinArbitrumaboutthebudgetwasmaintained.However,webelievethatthebudgetallocationplanislackingindetails;weexpectthatthisproblemwillberesolvedinthefuturethankstothetransparencyreportsfromArbitrum.

2.OperatingBudget
Arbitrumpromisestopublishatransparencyreportifitisdeterminedthatthebudgetisnotbeinghandledasstatedintheplan.Becausethebudgetdistributionlackssufficientclarity,webelievethattransparencyreportsmustbepublished.Weareinfavorofdoingso.

3.EcosystemGrowthInitiatives

Partnerships,grants,andeventsmentionedintheplanwillundoubtedlyfosterecosystemgrowth.WesupportArbitrum’sbudgetforthegrowthofitsecosystem;wesimplyhopethattheyareclearandhonestanddonotendupchangingthebudget.

4.TransparencyReports
Itisafactthatthesereportsmustexistfortransparencymonitoring.Arbitrum’sdecisiontoendorsethisapproachinresponsetocommunityandonlineforumrequestsisawiseone.Despitethefactthatwedonotbelievethatthereisaproblemrightnow,wewantthereportstobemorein-depthinthefuture.WeapplaudArbitrumforcreatingsolutionsinaccordancewiththecommunity’spreferencesandanticipatethatitwillkeepmovinginthatdirection.

Welookedattheideaandcametotheconclusionswedid.Therefore,wemadethedecisiontovote“for”.Again,manythankstoArbitrum.

ThefloodwepostedforAIP1.1andAIP1.2duringtheSnapshotvote:https://twitter.com/itublockchain/status/1648989259712348160?s=46&t=hGD89a6tl7pW8rFWA7BnNw8

15

19dayslater

ClosedonJul11,2023
`